version: '1'

services:
  # containers
  app:
    build:
      context: ./codeeducation # Pasta do Dockerfile
      dockerfile: Dockerfile.old
    images: juniorgunner/codeeducation
    container_name: hello_go
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker_entrypoint.sh
    networks:
      - my_network
    ports:
      - "8080:80"
    depends_on:
      - db

  # MySQL
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0 # Específico para dar boot no MySQL
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    enviroment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network


  networks:
    node_network:
      driver: bridge
